### ISSUE TITLE
Exclude element without reading his full info

### ISSUE THREAD

**Issue by g-rodigy** [xeokit/xeokit-convert#109]
When I try to convert ifc model wich has element IfcGrid without axis names, parse failing even if set `excludeTypes: ['IfcGrid']`.

Code example
````js
const {convert2xkt} = require('@xeokit/xeokit-convert/dist/convert2xkt.cjs.js')
const WebIFC = require('web-ifc/web-ifc-api-node.js')

const file = 'path/to/model'
const output = 'path/to/output'

convert2xkt({
    WebIFC,
    source: file,
    output,
    excludeTypes: ['IfcGrid'],
})
````

Log output:
````shell
INFO:  Parsing Model using IFC2X3 Schema
TypeError: Cannot read properties of null (reading 'map')
    at 3009204131 (...\node_modules\web-ifc\web-ifc-api-node.js:12645:381)
    at IfcAPI2.GetLine (....\node_modules\web-ifc\web-ifc-api-node.js:63239:84)
    at ...\node_modules\@xeokit\xeokit-convert\dist\convert2xkt.cjs.js:15944:51
    at Array.forEach (<anonymous>)
    at parseRelatedItemsOfType (...\node_modules\@xeokit\xeokit-convert\dist\convert2xkt.cjs.js:15942:25)
    at parseSpatialChildren (...\node_modules\@xeokit\xeokit-convert\dist\convert2xkt.cjs.js:15890:5)
    at ...\node_modules\@xeokit\xeokit-convert\dist\convert2xkt.cjs.js:15946:21
    at Array.forEach (<anonymous>)
    at parseRelatedItemsOfType (...\node_modules\@xeokit\xeokit-convert\dist\convert2xkt.cjs.js:15942:25)
    at parseSpatialChildren (...\node_modules\@xeokit\xeokit-convert\dist\convert2xkt.cjs.js:15882:5)
`````

**Comment by xeolabs** [comment]
Looks like an issue with `web-ifc`..

**Comment by g-rodigy** [comment]
Yes, it is `web-ifc` issue, but i mean can skip element before fully reading his data?

**Comment by xeolabs** [comment]
If I understand correctly, we have no means to configure conversion to ignore certain IFC elements by ID. This seems to be a useful potential feature though, but outside of our priorities at the moment. If anyone has time for to make a PR, I'd consider merging that though.
