### ISSUE TITLE
V1.1.3 SyntaxError: Unexpected token when using custom metadata file

### ISSUE THREAD

**Issue by mlankamp** [xeokit/xeokit-convert#79]
We use Creoox ifc2gltf to convert ifc files into the xkt format. We convert the file with the following commands:

```
ifc2gltf -i luchtbehandelingsbuis.ifc -o luchtbehandelingsbuis.glb -m luchtbehandelingsbuis.json
xeokit-convert -s luchtbehandelingsbuis.glb -m luchtbehandelingsbuis.json -o luchtbehandelingsbuis.xkt
````

The json file created by ifc2gltf contains all the propertysets from the ifc file. To keep the xkt as small as possible, we create a custom json-file. We do this using our xeokit-metadata tool (https://github.com/mlankamp/xeokit-metadata)

```
ifc2gltf -i luchtbehandelingsbuis.ifc -o luchtbehandelingsbuis.glb -m luchtbehandelingsbuis.json
metadata luchtbehandelingsbuis.ifc metadata.json
xeokit-convert -s luchtbehandelingsbuis.glb -m metadata.json -o luchtbehandelingsbuis.xkt
```

The xkt file is generated successfully, but when it's loaded into the viewer it gives an error in the console:
```javascript
Uncaught SyntaxError: Unexpected token 'g', "glTF
    at JSON.parse (<anonymous>)
    at inflate (xeokit-sdk.es.js:114073:1)
    at Object.parse (xeokit-sdk.es.js:114631:1)
    at XKTLoaderPlugin._parseModel (xeokit-sdk.es.js:115518:1)
    at xeokit-sdk.es.js:115481:1
    at request.onreadystatechange (xeokit-sdk.es.js:104361:1)
```

**Comment by mlankamp** [comment]
Doing the same with the open source tools:
```
IfcConvert --use-element-guids luchtbehandelingsbuis.ifc luchtbehandelingsbuis.glb
metadata luchtbehandelingsbuis.ifc metadata.json
xeokit-convert -s luchtbehandelingsbuis.glb -m metadata.json -o luchtbehandelingsbuis.xkt
```
 the output log:
```
[convert2xkt] Running convert2xkt v1.1.3...
[convert2xkt] Reading input file: luchtbehandelingsbuis.glb
[convert2xkt] Input file size: 2.67 kB
[convert2xkt] Reading input metadata file: metadata.json
[convert2xkt] Using parser: parseGLTFIntoXKTModel
[convert2xkt] Parsing normals: enabled
[convert2xkt] Parsing textures: enabled
[convert2xkt] Input file parsed OK. Building XKT document...
[convert2xkt] XKT document built OK. Writing to XKT file...
[convert2xkt] Converted to: XKT v10
[convert2xkt] XKT size: 3.75 kB
[convert2xkt] XKT textures size: 0.01kB
[convert2xkt] Compression ratio: 0.71
[convert2xkt] Conversion time: 0.05 s
[convert2xkt] Converted metaobjects: 0
[convert2xkt] Converted property sets: 0
[convert2xkt] Converted drawable objects: 1
[convert2xkt] Converted geometries: 1
[convert2xkt] Converted textures: 0
[convert2xkt] Converted textureSets: 0
[convert2xkt] Converted triangles: 32
[convert2xkt] Converted vertices: 48
[convert2xkt] Converted UVs: 0
[convert2xkt] Converted normals: 48
[convert2xkt] minTileSize: 200
[convert2xkt] Writing XKT file: luchtbehandelingsbuis.xkt
[convert2xkt] Done.
```

The result is the same.

**Comment by mlankamp** [comment]
If I downgrade to version `1.1.2` the xkt works, and I see that this version is smaller:

| version | size (bytes) |
| --- | --- | 
| 1.1.2 | 1189 |
| 1.1.3 | 3774 |

**Comment by mlankamp** [comment]
I did some additional testing, it only seems to be happening with smaller files.

**Comment by mlankamp** [comment]
Tested with version 1.1.4, it works!
