### ISSUE TITLE
When converting i recieve a type error

### ISSUE THREAD

**Issue by Raukie** [xeokit/xeokit-convert#90]
i run this command
`node convert2xkt.js -s "Gemeinschaftsschule_ARC.ifc" -o "Gemeinschaftsschule_ARC.xkt"`

then i get this output

`
(node:17316) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Error: TypeError: fetch failed
`

When building this error also occured to me:

`
[!] TypeError: The "path" argument must be of type string. Received an instance of Array
TypeError: The "path" argument must be of type string. Received an instance of Array
    at new NodeError (node:internal/errors:393:5)
    at validateString (node:internal/validators:163:11)
    at Object.resolve (node:path:167:9)
    at getConfigPath (C:\Users\revertz\Desktop\xkt converter\node_modules\@xeokit\xeokit-convert\node_modules\rollup\dist\bin\rollup:1594:23)
    at getConfigs (C:\Users\revertz\Desktop\xkt converter\node_modules\@xeokit\xeokit-convert\node_modules\rollup\dist\bin\rollup:1690:34)
    at runRollup (C:\Users\revertz\Desktop\xkt converter\node_modules\@xeokit\xeokit-convert\node_modules\rollup\dist\bin\rollup:1665:49)
    at Module.<anonymous> (C:\Users\revertz\Desktop\xkt converter\node_modules\@xeokit\xeokit-convert\node_modules\rollup\dist\bin\rollup:1714:5)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
`

Doing it with logging on i recieve this:
`
[convert2xkt] Running convert2xkt v1.1.6...
[convert2xkt] Reading input file: Gemeinschaftsschule_ARC.ifc
[convert2xkt] Input file size: 97800.13 kB
[convert2xkt] Using parser: parseIFCIntoXKTModel
(node:30704) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
    at emitExperimentalWarning (node:internal/util:227:11)
    at fetch (node:internal/process/pre_execution:215:5)
    at instantiateAsync (C:\Users\revertz\Desktop\xkt converter\node_modules\@xeokit\xeokit-convert\node_modules\web-ifc\web-ifc-api-node.js:6690:22)
    at createWasm (C:\Users\revertz\Desktop\xkt converter\node_modules\@xeokit\xeokit-convert\node_modules\web-ifc\web-ifc-api-node.js:6711:11)
    at C:\Users\revertz\Desktop\xkt converter\node_modules\@xeokit\xeokit-convert\node_modules\web-ifc\web-ifc-api-node.js:10885:19
    at IfcAPI2.<anonymous> (C:\Users\revertz\Desktop\xkt converter\node_modules\@xeokit\xeokit-convert\node_modules\web-ifc\web-ifc-api-node.js:53899:33)
    at Generator.next (<anonymous>)
    at C:\Users\revertz\Desktop\xkt converter\node_modules\@xeokit\xeokit-convert\node_modules\web-ifc\web-ifc-api-node.js:43:61
    at new Promise (<anonymous>)
    at __async (C:\Users\revertz\Desktop\xkt converter\node_modules\@xeokit\xeokit-convert\node_modules\web-ifc\web-ifc-api-node.js:27:10)
Error: TypeError: fetch failed
`

which makes me think it is in the parser since the file in which it is called does not contain an call to fetch

**Comment by Raukie** [comment]
I have found the solution to it
`$ node --no-experimental-fetch ... `

Just add the --no-experimental-fetch to the command so it doesn't use experimental fetch.
The issue was indeed in the parser. To be more precise the web ifc api.

As fix you could also downgrade to node version 16 but with the flag that is not necessary
